### ISSUE TITLE
Ok to Contribute? 

### ISSUE THREAD

**Issue by Qd0t** [Jaxe-Dev/RimHUD#11]
Hey, I added few things to this on my end and figured you might find some of them usefull (preview image attached).
Since I don't see the licence this is under I'm not sure if you are ok if I just post the files here, so let me know if you are interested in this and I can send the files to you directly if you want (you don't have to credit me, I just want to share this)

Changes include things like:

-current instant level of mood displayed over the mood bars with a white bar

-Added player/other mech target selector

-Guilt icon indicator w/ tooltip

-Inspired Icon w/ tt + Info

-added GCLF to Prisoner info as Conversion efficiency
	
-threashhold bars are Thicker and shorter.

-included infection severity/immune in tool tip- worst case of 'infection' in label (Color coded when severity>Immunity and when tended)

-quick LMB/RMB medical care picker

The rest is rather custom for my use.

There are few things I could use your help with as well. I have some allignment issues with the added target selectors that I can't get to fit properly, and there are some offsets for the vector positions of the threshhold bars that I dirty corrected, they might be due to the rounding in GetHgrid (not sure how important that rounding is). I haven't played with it much but that second thresh bar on food is still offset even tho I made some corrections.

Thanks for the mod, I learned a lot from it.
![Untitled-1](https://user-images.githubusercontent.com/88070148/206074477-dc12b1cb-2b3c-40ed-898a-1378ee676ffb.png)

**Comment by timibox** [comment]
Hi, I have a requirement. Can RimHUD add basic description information for all information card labels？
`<img src="https://media.discordapp.net/attachments/499271866238763008/1063006672341192744/NAPLJQ6CO98202JFTGO.png">`
like this

**Comment by Jaxe-Dev** [comment]
Sorry I'm not very active in GitHub so I didn't notice your post. Your work does look very interesting but as of this moment any code contributions would probably make things a little harder for me to keep track of and I've just pushed an update which revamps the code in many places. The new update does however allow third-party widgets so perhaps any new widgets you added could be brought in your own submod. If you could contact me on Discord perhaps we can chat a bit more and see where that leads about implementing some of your changes because they do look very good.
